### ISSUE TITLE
Demo link ?

### ISSUE THREAD

**Issue by heyadityak** [dhruvp-8/IOChatWebApp#1]
Can you send the project link for the final outcome ? @dhruvp-8

**Comment by dhruvp-8** [comment]
https://fathomless-eyrie-24083.herokuapp.com/
Still I am working on validations!

 Saturday, January 28, 2017, Aditya Krishnakumar <notifications@github.com>
wrote:

**Comment by heyadityak** [comment]
multiple sessions can happen even in multiple tabs

**Comment by heyadityak** [comment]
also, multiple sessions with user having same username are also allowes

**Comment by heyadityak** [comment]
https://github.com/sindresorhus/awesome-nodejs

A small reference for awesome libraries & modules
